"""Add unique check to blob name

Revision ID: ea57d90019b8
Revises: e4d9139c6f40
Create Date: 2025-03-09 12:15:12.843725

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ea57d90019b8'
down_revision: Union[str, None] = 'e4d9139c6f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blobs', schema="BCS") as batch_op:
        batch_op.create_unique_constraint('uq_blobs_name', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blobs', schema="BCS") as batch_op:
        batch_op.drop_constraint('uq_blobs_name', type_='unique')
    # ### end Alembic commands ###
