PRACTICE_EFFECT = 0.02
COMPETITION_EFFECT = 0.025
OVERTAKE_EFFECT = 0.0005
ADVENTURE_EFFECT = 0.01

MAINTENANCE_COST = 52
MAINTENANCE_EFFECT = 32

HEIR_COST = 320
PREMIUM_PRACTICE_COST = 36

LABOUR_SALARY = 1
GRANDMASTER_SALARY = 2
VICTORY_PRIZE = 1
CHAMPION_PRIZE = 4
GRANDMASTER_PRIZE = 8
ROOKIE_OF_THE_YEAR_PRIZE = 1

MAX_FIELD_SIZE = 24
MIN_FIELD_SIZE = 5
MAX_LEAGUE_COUNT = 3

QUEUE_LEVEL = 10

EPOCHS_PER_SEASON = 32
CYCLES_PER_EPOCH = 4
SEASONS_PER_EON = 4

CYCLES_PER_SEASON = EPOCHS_PER_SEASON * CYCLES_PER_EPOCH
CYCLES_PER_EON = CYCLES_PER_SEASON * SEASONS_PER_EON

INITIAL_INTEGRITY = CYCLES_PER_SEASON * 32

BLOB_CREATION_RESOURCES = CYCLES_PER_SEASON

# Factory production is split into 4 parts: a constant base output plus solar,
# wind and hydro outputs which depend on the current weather and wind strength.
BASE_FACTORY_OUTPUT = 1
SOLAR_MAX_OUTPUT = 1
WIND_MAX_OUTPUT = 1
HYDRO_MAX_OUTPUT = 1
