PRACTICE_EFFECT = 0.01
COMPETITION_EFFECT = 0.02
OVERTAKE_EFFECT = 0.0004
OVERTAKEN_EFFECT = 0.0001

MAINTENANCE_COST = 32
MAINTENANCE_EFFECT = 32

LABOUR_SALARY = 1
VICTORY_PRIZE = 1
CHAMPION_PRIZE = 4
GRANDMASTER_PRIZE = 8

MAX_FIELD_SIZE = 24
MIN_FIELD_SIZE = 5
MAX_LEAGUE_COUNT = 3

QUEUE_LEVEL = 10

EPOCHS_PER_SEASON = 32
CYCLES_PER_EPOCH = 4
SEASONS_PER_EON = 4

CYCLES_PER_SEASON = EPOCHS_PER_SEASON * CYCLES_PER_EPOCH
CYCLES_PER_EON = CYCLES_PER_SEASON * SEASONS_PER_EON

INITIAL_INTEGRITY = CYCLES_PER_SEASON * 32

BLOB_CREATION_RESOURCES = CYCLES_PER_SEASON
